repos:
    - repo: https://github.com/biobuddies/helicopyter
      rev: v2026.00.01
      hooks:
          - id: actionlint
          - id: basedpyright
          - id: cookiecutter
          - id: end-of-file-fixer
          - id: hadolint
          - id: mailmap
          - id: prettier-write
          - id: ruff-check-fix
          - id: ruff-format
          - id: shellcheck
          - id: trailing-whitespace-fixer
          - id: typos
          - id: validate-pyproject
          - id: uv-pip-check
          - id: uv-pip-compile
          - id: yamllint
